INSERT INTO TAX_RATE values('A', 10);
INSERT INTO TAX_RATE values('B', 20);
INSERT INTO TAX_RATE values('C', 0);

INSERT INTO ITEMS values('HANGER',650,'C');
INSERT INTO ITEMS values('PANT',3500,'A');
INSERT INTO ITEMS values('BAG',1000,'B');
INSERT INTO ITEMS values('SKIRT',800,'A');
INSERT INTO ITEMS values('SHIRT',1500,'A');