DROP TABLE IF EXISTS ITEMS;  
CREATE TABLE ITEMS (
ITEM_NAME VARCHAR_IGNORECASE(20) PRIMARY KEY,
PRICE DOUBLE(6) NOT NULL, 
CATEGORY VARCHAR(1) NOT NULL);

DROP TABLE IF EXISTS TAX_RATE;  
CREATE TABLE TAX_RATE (
CATEGORY VARCHAR(1) PRIMARY KEY,
TAX INT(2)
);

ALTER TABLE ITEMS
ADD FOREIGN KEY(CATEGORY) 
REFERENCES TAX_RATE(CATEGORY) 


